export const getTranslatedProjects = (t) => [
  {
    id: 1,
    title: t("projects.trekio.title"),
    description: t("projects.trekio.description"),
    href: "https://trekio.net/login",
    logo: "",
    image: "/assets/p2.png",
    tags: [
      { id: 1, name: "React.Js" },
      { id: 2, name: "Tailwind" },
      { id: 3, name: "Inertia.js" },
      { id: 5, name: "TypeScript" },
    ],
  },
  {
    id: 9,
    title: t("projects.medibroking.title"),
    description: t("projects.medibroking.description"),
    href: "https://medibroking.com/products",
    logo: "",
    image: "/assets/medibroking.png",
    tags: [
      { id: 1, name: "Node.js" },
      { id: 2, name: "SQL" },
      { id: 3, name: "React.Js" },
      { id: 4, name: "Tailwind" },
    ],
  },
  {
    id: 10,
    title: t("projects.beetsah.title"),
    description: t("projects.beetsah.description"),
    href: "https://beetsah.com/en?country=ae",
    logo: "",
    image: "/assets/beetsah.png",
    tags: [
      { id: 1, name: "Node.js" },
      { id: 2, name: "SQL" },
      { id: 3, name: "React.Js" },
      { id: 4, name: "Tailwind" },
    ],
  },
  {
    id: 11,
    title: t("projects.disil.title"),
    description: t("projects.disil.description"),
    href: "https://disil.vercel.app/",
    logo: "",
    image: "/assets/disil.png",
    tags: [
      { id: 1, name: "Node.js" },
      { id: 2, name: "SQL" },
      { id: 3, name: "React.Js" },
      { id: 4, name: "Tailwind" },
    ],
  },
  {
    id: 12,
    title: t("projects.gamersStation.title"),
    description: t("projects.gamersStation.description"),
    href: "https://medibroking.com/products",
    logo: "",
    image: "/assets/Screenshot 2026-09-09 105601.png",
    tags: [
      { id: 1, name: "Node.js" },
      { id: 2, name: "SQL" },
      { id: 3, name: "React.Js" },
      { id: 4, name: "Tailwind" },
    ],
  },
  {
    id: 2,
    title: t("projects.elmullim.title"),
    description: t("projects.elmullim.description"),
    href: "",
    logo: "",
    image: "/assets/p6.png",
    tags: [
      { id: 1, name: "React.Js" },
      { id: 2, name: "Tailwind" },
      { id: 3, name: "TypeScript" },
    ],
  },
  {
    id: 3,
    title: t("projects.foodOrdering.title"),
    description: t("projects.foodOrdering.description"),
    href: "https://complete-food-delivery-psi.vercel.app/",
    logo: "",
    image: "/assets/p5.png",
    tags: [
      { id: 1, name: "React.Js" },
      { id: 2, name: "Tailwind" },
    ],
  },
  {
    id: 7,
    title: t("projects.hotel.title"),
    description: t("projects.hotel.description"),
    href: "https://www.youtube.com/watch?v=dUNvwVdmd98",
    logo: "",
    image: "/assets/p10.png",
    tags: [
      { id: 1, name: "React.Js" },
      { id: 2, name: "Tailwind" },
      { id: 3, name: "Clerk" },
      { id: 4, name: "React Router" },
    ],
  },
  {
    id: 8,
    title: t("projects.portfolio.title"),
    description: t("projects.portfolio.description"),
    href: "/",
    logo: "",
    image: "/assets/p1.png",
    tags: [
      { id: 1, name: "React.Js" },
      { id: 2, name: "Tailwind" },
      { id: 3, name: "MagicUI" },
    ],
  },
  {
    id: 4,
    title: t("projects.factoryPro.title"),
    description: t("projects.factoryPro.description"),
    href: "https://factorypro-sand.vercel.app/",
    logo: "",
    image: "/assets/p3.png",
    tags: [
      { id: 1, name: "Next.Js" },
      { id: 2, name: "Tailwind" },
    ],
  },
  {
    id: 5,
    title: t("projects.coffeeShop.title"),
    description: t("projects.coffeeShop.description"),
    href: "https://coffee-beryl-six.vercel.app/",
    logo: "",
    image: "/assets/p8.png",
    tags: [
      { id: 1, name: "Next.Js" },
      { id: 2, name: "Tailwind" },
    ],
  },
  {
    id: 6,
    title: t("projects.ecommerce.title"),
    description: t("projects.ecommerce.description"),
    href: "https://forever-tau-ecru.vercel.app/",
    logo: "",
    image: "/assets/p4.png",
    tags: [
      { id: 1, name: "Next.Js" },
      { id: 2, name: "Tailwind" },
      { id: 3, name: "Redux" },
      { id: 4, name: "Axios" },
    ],
  },
];

export const getTranslatedExperiences = (t) => [
  {
    title: t("experiences.deltaDev.title"),
    job: t("experiences.deltaDev.job"),
    date: t("experiences.deltaDev.date"),
    contents: [
      t("experiences.deltaDev.p1"),
      t("experiences.deltaDev.p2"),
      t("experiences.deltaDev.p3"),
    ],
  },
  {
    title: t("experiences.sync8.title"),
    job: t("experiences.sync8.job"),
    date: t("experiences.sync8.date"),
    contents: [
      t("experiences.sync8.p1"),
      t("experiences.sync8.p2"),
      t("experiences.sync8.p3"),
      t("experiences.sync8.p4"),
      t("experiences.sync8.p5"),
    ],
  },
  {
    title: t("experiences.freelance.title"),
    job: t("experiences.freelance.job"),
    date: t("experiences.freelance.date"),
    contents: [
      t("experiences.freelance.p1"),
      t("experiences.freelance.p2"),
      t("experiences.freelance.p3"),
      t("experiences.freelance.p4"),
      t("experiences.freelance.p5"),
      t("experiences.freelance.p6"),
    ],
  },
];

export const myProjects = getTranslatedProjects((key) => key);
export const experiences = getTranslatedExperiences((key) => key);
